### ISSUE TITLE
Einführung Technischer Bericht

### ISSUE THREAD

**Issue by lukasmartinelli** [manuelroth/osm2vectortiles-thesis#11]
So sieht man den Mehrwert konkret und was wir lösen.
- [ ] Vorher / Nachher
- [x] Ziele
- [x] Vorgehen

**Comment by manuelroth** [comment]
Wie sehen die Rahmenbedingung für unser Projekt aus?
- Es gab ja keine spezifischen Bedingungen seitens Herr Keller (ihr müsst Postgres verwenden)

**Comment by lukasmartinelli** [comment]
> Wie sehen die Rahmenbedingung für unser Projekt aus?

Ja doch von wegen "Python" und so. Aber wir müssten den Antrag nochmals zu Gesicht bekommen... :smile:

**Comment by manuelroth** [comment]
This issue was moved to osm2vectortiles/osm2vectortiles-thesis#10
