### ISSUE TITLE
Meeting 6. Woche

### ISSUE THREAD

**Issue by lukasmartinelli** [manuelroth/osm2vectortiles-thesis#27]
## Fragen
- OSM Carto CSS auf Vektortiles basierend - kann von Praktikant erstellt werden?
- Wir sollen wir Prios einiger zusätzlichen Tasks in FINAL milestone setzen?
## Entscheidungen
- Manuel erstellt tm2source, Lukas parallelisiert Rendern
- Rendering Infrastruktur wird von klokantech zur Verfügung gestellt
- Infrastruktur soll verteilte Renderer unterstützen (theoretisch klokantech + HSR + hostfactory möglich)
## Gemacht
- Elaboration Milestone abgeschlossen
- Mit Petr Eintscheidungen und nächste Schritte definiert
- Wasser Import
- CI Infrastruktur und Docker Compose Setup
## Schwierigkeiten
- HSR Server stürzt immer noch ab
- Wird es zeitlich anspruchsvoll mit Analyse zusammen (BETA Milestone in 3 Wochen)

**Comment by lukasmartinelli** [comment]
> OSM Carto CSS auf Vektortiles basierend - kann von Praktikant erstellt werden?

Praktikant wird zur Verfügung gestellt.
- [ ] Abklären CartoCSS mit Vektortiles oder gleich Mapbox GL
- [ ] Ist es überhaupt möglich wie das originale Projekt darzustellen

**Comment by manuelroth** [comment]
- [ ] Import Water mit landuse erweitern

**Comment by lukasmartinelli** [comment]
Statistik wirklich nehmen um unseres Projekt zu testen.
Statistik ist doch wichtig, wenn innerhalb vom Testen merkt, dass es einen Pain point gibt soll er umgesetzt werden.

**Comment by manuelroth** [comment]
- [Thunderforest](http://thunderforest.com) bietet Vector Tile hosting an
