### ISSUE TITLE
Meeting 8

### ISSUE THREAD

**Issue by manuelroth** [manuelroth/osm2vectortiles-thesis#30]
# Gemacht
- Natural Earth Daten integriert (hauptsächlich Zoomlevel 0 - 5) DEMO
- Scalerank mit Natural Earth Scalerank ersetzt (wurde zuvor mit population oder area berechnet)
# Schwierigkeiten
- Scalerank für viele Layers (Places, Country, Marine) haben nicht mit mapbox streets v6 übereingestummen
# Plan
- Wasser ausschliessen
- Projekt abschliessen und mit Dokumentation starten
- Rendering starten
# BBox für Country Extracts
- Wir möchten möglichst ähnliche Extracts wie http://download.geofabrik.de/ anbieten
- BBox kann mit http://tools.geofabrik.de/calc/ herausgefunden werden.
- Am liebsten hätten wir ein CSV in folgender Form:

``` csv
country;left;bottom;right;top;
germany;5.53;47.23;15.74;55.38
switzerland;5.92;45.71;10.71;47.86
```

**Comment by lukasmartinelli** [comment]
Inhaltsverzeichnis vorbereiten und anhand von dem besprechen.
