### ISSUE TITLE
Bewertung / Evaluation unserer Lösung

### ISSUE THREAD

**Issue by lukasmartinelli** [manuelroth/osm2vectortiles-thesis#32]
Stefan Keller fragen um was es bei **3. Bewertung geht**

**Comment by lukasmartinelli** [comment]
Was ist neuartig an unserer Arbeit?
Wann haben wir es geschafft?
Welche Deliverables?
Was für Abweichungen gab es vom Ziel?
Ausblick

**Comment by manuelroth** [comment]
This issue was moved to osm2vectortiles/osm2vectortiles-thesis#3
