### ISSUE TITLE
Evaluation 

### ISSUE THREAD

**Issue by lukasmartinelli** [manuelroth/osm2vectortiles-thesis#33]
- Tileserver
- Import
- Vector Tile Format (??? abklären mit Stefan Keller)
- Datenbank (wieso PostGIS?) auf Open Streetmap Wiki (dort steht wieso PostgreSQL)
- Datenquellen: wieso Natural Earth?, wieso Grenzen separat? 
  -mojodna/tl vs mapbox/tilelive
- AWS SQS? wieso nicht RabbitMQ
- AWS / Google Cloud (sollen wir überhaupt reinnehmen?
- AWS Logging?
- Wieso pgbouncer vs andere Balancer

Wahrscheinlich macht es Sinn die Evaluation erst zu bringen, wenn der ganze Workflow klar ist.

**Comment by manuelroth** [comment]
This issue was moved to osm2vectortiles/osm2vectortiles-thesis#2
